name: Add Rules to Cloudflare Gateway 
on:
  #push:
  #schedule:
    #- cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  run:
    name: Creat rules 
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Cloudflare Gateway 
        run: bash build.sh
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
